### ISSUE TITLE
RNA *

### ISSUE THREAD

**Issue by augustearth** [pennbiobank/penn-lims-ontology#6]
Generic, cytoplasmic, nuclear, etc...  Follow up with scientists about definitions.

**Comment by augustearth** [comment]
Related to #4.  We will follow the same process here.  There are processes that will create RNA extracts that are generic, cytoplasmic, nuclear, etc...

@taralmc will review.

**Comment by taralmc** [comment]
There are a bunch of specific RNA and DNA types that are in caTISSUE, but none of these have been used. If they are not used in LV either I think we do not need to include them in our list. (I did not map them to OBI for this reason. If others feel they should remain in the list then I will try to map them.)

**Comment by augustearth** [comment]
The sub-types of RNA (extract) are currently unused, so we will just go with RNA Extract.
